# Generated by Django 5.1.4 on 2024-12-10 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoria')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Dibujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sin titulo', max_length=100, verbose_name='Titulo del dibujo')),
                ('imagen', models.ImageField(upload_to='dibujos/', verbose_name='Imagen del dibujo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion del dibujo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.categoria', verbose_name='Categoria del dibujo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador del dibujo')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=256, verbose_name='Texto del comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ha añadido el comentario')),
                ('dibujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.dibujo', verbose_name='Dibujo al que se le ha añadido el comentario')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='lista_dibujos',
            field=models.ManyToManyField(related_name='categorias', to='drawing.dibujo', verbose_name='Lista de dibujos en la categoria'),
        ),
        migrations.CreateModel(
            name='Estrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.dibujo', verbose_name='Dibujo asignado a la estrella')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ha hecho la estrella')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(max_length=256, verbose_name='Motivo del reporte')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del reporte')),
                ('dibujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.dibujo', verbose_name='Dibujo que ha sio reportado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ha reportado el dibujo')),
            ],
        ),
    ]
